action_id: trunk-share-with-everyone
date: 2024-09-26 08:03:20
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1727337800
full_timestamp:
  nanos: 324760000
  seconds: 1727337800
trunk_version: 1.22.5
